AWSTemplateFormatVersion: '2010-09-09'
Description: Create 3 private S3 buckets with PublicAccessBlock and optional versioning.

Parameters:
  ProjectPrefix:
    Type: String
    Default: denishakbari-8901001
    AllowedPattern: '^[a-z0-9-]+$'
    Description: Lowercase, hyphenated prefix used in bucket names.
  EnableVersioning:
    Type: String
    Default: 'true'
    AllowedValues: ['true','false']
    Description: Enable versioning on all buckets (true/false).

Conditions:
  DoVersioning: !Equals [ !Ref EnableVersioning, 'true' ]

Resources:
  BucketA:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - "-"
        - - !Ref ProjectPrefix
          - s3a
          - !Select [2, !Split ["/", !Ref "AWS::StackId"]]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: !If [ DoVersioning, Enabled, Suspended ]

  BucketB:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - "-"
        - - !Ref ProjectPrefix
          - s3b
          - !Select [2, !Split ["/", !Ref "AWS::StackId"]]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: !If [ DoVersioning, Enabled, Suspended ]

  BucketC:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - "-"
        - - !Ref ProjectPrefix
          - s3c
          - !Select [2, !Split ["/", !Ref "AWS::StackId"]]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: !If [ DoVersioning, Enabled, Suspended ]

Outputs:
  BucketAName:
    Value: !Ref BucketA
  BucketBName:
    Value: !Ref BucketB
  BucketCName:
    Value: !Ref BucketC
