AWSTemplateFormatVersion: '2010-09-09'
Description: Public RDS MySQL (for project demo). NOT for production use.

Parameters:
  ProjectPrefix:
    Type: String
    Default: prog8870
  DBName:
    Type: String
    Default: appdb
  MasterUsername:
    Type: String
    Default: adminuser
  MasterUserPassword:
    Type: String
    NoEcho: true

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.2.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true

  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.2.1.0/24
  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.2.2.0/24

  RDSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL (Project Demo Only)
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  DBSubnets:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for RDS
      SubnetIds: [!Ref SubnetA, !Ref SubnetB]

  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      Engine: mysql
      EngineVersion: "8.0"
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      VPCSecurityGroups: [!Ref RDSSG]
      DBSubnetGroupName: !Ref DBSubnets
      PubliclyAccessible: true
      DeletionProtection: false
      BackupRetentionPeriod: 0
      MultiAZ: false

Outputs:
  RDSEndpoint:
    Value: !GetAtt MyDB.Endpoint.Address
  RDSPublicAccessibility:
    Value: !Ref MyDB
    Description: DB Instance logical ID (indicates creation). PubliclyAccessible is true.
